# Generated by Django 3.2.5 on 2021-09-22 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBInfos',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('host', models.CharField(help_text='主机地址', max_length=50, verbose_name='主机地址')),
                ('user', models.CharField(help_text='用户名', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(help_text='密码', max_length=50, verbose_name='密码')),
                ('database', models.CharField(help_text='数据库名称', max_length=50, unique=True, verbose_name='数据库名称')),
                ('port', models.IntegerField(help_text='端口', verbose_name='端口')),
            ],
            options={
                'verbose_name': '数据库信息',
                'verbose_name_plural': '数据库信息',
                'db_table': 'gk_dbinfos',
            },
        ),
        migrations.CreateModel(
            name='DBLogs',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('sql', models.CharField(help_text='执行的sql', max_length=200, verbose_name='执行的sql')),
                ('database', models.ForeignKey(help_text='数据库信息', on_delete=django.db.models.deletion.CASCADE, related_name='dblogs', to='dbsapi.dbinfos', verbose_name='数据库信息')),
            ],
            options={
                'verbose_name': '执行sql的日志信息',
                'verbose_name_plural': '执行sql的日志信息',
                'db_table': 'gk_dblogs',
            },
        ),
    ]
